### ISSUE TITLE
Typo in usage (wetzel.js -h)

### ISSUE THREAD

**Issue by scurest** [AnalyticalGraphicsInc/wetzel#26]
[Here](https://github.com/AnalyticalGraphicsInc/wetzel/blob/668480165326e16d3ced34c7fa649304470853b9/bin/wetzel.js#L16-L18). The first line is missing a trailing `+` and all of them are missing newlines at the end of the strings.

**Comment by pjcozzi** [comment]
Thanks @scurest!  Any chance you have the time to open a pull request with the fix.

See the short contributing section here: https://github.com/AnalyticalGraphicsInc/wetzel#contributions

**Comment by scurest** [comment]
I would, but I don't really want to mess around with the CLA, sorry 😑

**Comment by pjcozzi** [comment]
The CLA is in place so that you **keep** the copyright to your code but allow the project to use it.  These are common - and a best practice - for well-established open-source projects.  For example: https://opensource.google.com/docs/cla/#why

Thanks for the report and I'm sure someone will fix this in the future.

**Comment by kinnerapriyap** [comment]
I could do this, if it's okay. 🙂

**Comment by pjcozzi** [comment]
Awesome, thanks @kinnerapriyap!

**Comment by kinnerapriyap** [comment]
PR sent. @pjcozzi 😀

**Comment by emackey** [comment]
Fixed in #28.
